"""English restatements of the ARDB corpus: deposits and loans.

Written by reading each Khmer page with its figures already converted to
English notation. Verified against the source by ardb.normalize.numbers_match.
"""

ENGLISH = {

"product-service-deposits": (
    "ARDB deposit accounts",
    "ARDB offers three kinds of deposit account: the demand deposit (current "
    "account), the fixed deposit (term deposit), and the savings deposit. Each "
    "has its own interest rates, minimum opening balance and document "
    "requirements, described on its own page."
),

"product-service-deposits-demand-deposit": (
    "Demand deposit (current account)",
    "The ARDB demand deposit is a current account. The annual interest rate is "
    "0.50% on US dollar balances and 0.75% on riel balances, and the same rates "
    "apply to individual and corporate accounts alike. The minimum initial "
    "deposit is 500 US dollars or 2 million riel.\n"
    "An individual opening the account needs the bank's individual account "
    "opening form and a national identity card or passport.\n"
    "A company needs the bank's corporate account opening form; the original "
    "identity card or passport of the authorised signatory; the original and "
    "most recent memorandum and articles of association signed by the company "
    "director; a commercial or corporate registration certificate issued by the "
    "Ministry of Commerce, or a QR-code registration certificate; the original "
    "board resolution appointing the signatory and setting the account mandate; "
    "the original identity card or passport of the company director and the "
    "shareholders; the business patent tax certificate if there is one; and any "
    "business licence issued by the relevant ministry or authority, if "
    "applicable."
),

"product-service-deposits-fixed-deposit": (
    "Fixed deposit (term deposit)",
    "The ARDB fixed deposit lets a customer place money for a set term and know "
    "in advance what it will earn. Terms run from 1 to 24 months and interest is "
    "paid at the end of the term.\n"
    "The annual rates are the same for individuals and companies, and the same "
    "in US dollars and in riel: 1.50% for a 1 month term, 2.00% for 3 months, "
    "2.75% for 6 months, 3.00% for 9 months, 4.00% for 12 months and 4.00% for "
    "24 months.\n"
    "The minimum initial deposit is 500 US dollars or 2 million riel.\n"
    "An individual needs the bank's individual account opening form and a "
    "national identity card or passport.\n"
    "A company needs the bank's corporate account opening form; the original "
    "identity card or passport of the authorised signatory; the original and "
    "most recent memorandum and articles of association signed by the company "
    "director; a commercial or corporate registration certificate issued by the "
    "Ministry of Commerce, or a QR-code registration certificate; the original "
    "board resolution appointing the signatory and setting the account mandate; "
    "the original identity card or passport of the company director and the "
    "shareholders; the business patent tax certificate if there is one; and any "
    "business licence issued by the relevant ministry or authority, if "
    "applicable."
),

"product-service-deposits-saving-deposit": (
    "Savings deposit",
    "The ARDB savings account pays an annual interest rate of 1.00%, the same in "
    "US dollars and in riel, and the same for individual and corporate "
    "accounts. The minimum initial deposit is 10 US dollars or 40,000 riel.\n"
    "An individual needs the bank's individual account opening form and a "
    "national identity card or passport.\n"
    "A company needs the bank's corporate account opening form; the original "
    "identity card or passport of the authorised signatory; the original and "
    "most recent memorandum and articles of association signed by the company "
    "director; a commercial or corporate registration certificate issued by the "
    "Ministry of Commerce, or a QR-code registration certificate; the original "
    "board resolution appointing the signatory and setting the account mandate; "
    "the original identity card or passport of the company director and the "
    "shareholders; the business patent tax certificate if there is one; and any "
    "business licence issued by the relevant ministry or authority, if "
    "applicable."
),

"product-service-loans": (
    "ARDB loan products",
    "ARDB offers eight loan products: credit to support small-scale "
    "agriculture; a special government programme loan for market intervention, "
    "covering development mechanisms and the operation of storage warehouses and "
    "dryers for rice, maize and other crops; a special loan under the 100 "
    "million US dollar financing programme to raise agricultural production, "
    "find markets and stabilise crop prices; wholesale credit; credit for women "
    "entrepreneurs in the agricultural and agro-industrial production chain; the "
    "green loan; credit for agricultural communities in the agricultural and "
    "agro-industrial value chain; and credit for small, medium and large "
    "enterprises in that same chain.\n"
    "To apply, contact the nearest ARDB branch or call 098 304 057, 023 220 810 "
    "or 023 220 811."
),

"product-service-loans-agri-production-market-credit": (
    "Special loan under the 100 million US dollar financing programme",
    "This is a special loan under the 100 million US dollar financing programme, "
    "intended to raise agricultural production, find markets and keep crop "
    "prices stable. It is a government intervention measure, urgent and "
    "temporary, with ARDB acting as the operator providing working capital to "
    "buy paddy, so as to steady domestic rice prices, increase supply for local "
    "processing, support food security and support exports.\n"
    "It is aimed at rice mill owners, rice milling, processing and exporting "
    "companies, paddy and rice collection centres, and other buyers or owners of "
    "paddy and rice warehouses and dryers who are willing and able to buy paddy "
    "at market prices or at another suitable set price.\n"
    "Requirements: the business owner must be a legal entity and a member of the "
    "Cambodia Rice Federation, registered and recognised by law or by the "
    "relevant supervisory authority; a good reputation and experience in the "
    "paddy and rice sector; warehouse capacity able to hold at least 3,000 "
    "tonnes of paddy; a dryer able to dry at least 50 tonnes of paddy per day; a "
    "paddy and rice stock warehouse meeting technical standards; fire prevention "
    "and suppression systems; the stock warehouse sited separately from the "
    "processing mill; clear reports or documents evidencing business income and "
    "expenditure; and sufficient cash flow to assure repayment.\n"
    "It is a short-term working capital loan. The loan size can be up to 80% of "
    "the value of the paddy and rice stock to be pledged. It is available in US "
    "dollars or riel, for a term of no more than 6 months, at an interest rate "
    "of 4% a year, with an administrative fee of 0.5% of the loan amount "
    "provided. Interest is paid monthly and the principal is repaid at the end "
    "of the term.\n"
    "Documents to apply: a copy of the Khmer national identity card and the "
    "family book or residence book; the articles of association and business "
    "licence recognised by the supervisory authority; a valid patent "
    "certificate; a stock declaration letter for paddy and rice; and supporting "
    "income and expenditure documents and any other required documents, if "
    "applicable."
),

"product-service-loans-agri-women-entrepreneur-credit": (
    "Credit for women entrepreneurs in the agricultural value chain",
    "This loan supports women entrepreneurs who own businesses in the "
    "agricultural and agro-industrial value chain. Both individuals and legal "
    "entities may apply.\n"
    "An applicant must meet 2 of these 4 conditions: the business owner or the "
    "owner's representative is a woman; most shareholders are women; most of the "
    "business's staff are women; or most members of the board or the management "
    "team are women. They must also have relevant experience and knowledge of "
    "the trade, clear reports or documents evidencing business income and "
    "expenditure, and sufficient cash flow to assure repayment.\n"
    "ARDB lends for seasonal working capital across the production cycle — "
    "supplying agricultural inputs, buying agricultural produce, storage, "
    "drying, processing and packing — and for investment capital for tools, "
    "equipment and machinery, building a factory or production premises, and "
    "other purposes.\n"
    "As short-term working capital: from 5,000 US dollars or the equivalent in "
    "riel, up to 20% of the bank's net own funds, for up to 36 months, at an "
    "interest rate from 7-9% a year, with an administrative fee of 0.5% of the "
    "loan amount charged once only. Interest is paid monthly and the principal "
    "is amortised monthly, quarterly, half-yearly or yearly, or according to the "
    "business's cash flow.\n"
    "As long-term investment capital: from 5,000 US dollars or the equivalent in "
    "riel, up to 20% of the bank's net own funds, for up to 7 years, at an "
    "interest rate from 8-11% a year, with an administrative fee of 0.5% of the "
    "loan amount charged once only, on the same repayment terms. Other "
    "conditions also apply.\n"
    "Documents to apply: a copy of the Khmer national identity card and the "
    "family book or residence book; property documents (hard title or soft "
    "title) to pledge as security; and supporting income and expenditure "
    "documents and any other required documents, if applicable."
),

"product-service-loans-small-scale-agriculture-credit": (
    "Credit to support small-scale agriculture",
    "This loan is for individuals working in or running their own business in "
    "the agricultural production chain: farming and plantation work, raising "
    "livestock, aquaculture, growing vegetables or fruit, starting or expanding "
    "industrial crops, buying and selling agricultural inputs, mixed "
    "agro-industrial processing, processing food from agricultural produce, "
    "processing semi-finished and finished products, small-scale trade connected "
    "to the agricultural production chain, and other areas tied to social and "
    "economic development.\n"
    "Requirements: the applicant must be an individual of Khmer nationality; "
    "have a clear place of residence and place of work and a good record; have "
    "relevant experience in the trade or business; and be willing to develop "
    "from farmer into entrepreneur.\n"
    "As working capital: 500-5,000 US dollars or the equivalent in riel, at an "
    "interest rate of 10% a year against a hard title and 11% a year against a "
    "soft title, for up to 36 months, with a processing cost of 1% a year on the "
    "outstanding loan balance.\n"
    "As investment capital: 5,000-20,000 US dollars or the equivalent in riel, "
    "at an interest rate of 8% a year against a hard title and 9% a year against "
    "a soft title, for up to 60 months, with a processing cost of 1% a year on "
    "the outstanding loan balance.\n"
    "Security is a hard title or a legally recognised soft title, or a fixed "
    "deposit certificate.\n"
    "The product's particular benefits are that the principal may be repaid "
    "early without penalty, that a guarantor's pledged property may be "
    "substituted, and that the interest rate is low for the agricultural "
    "sector.\n"
    "Documents required: a copy of the Khmer national identity card and the "
    "family book or residence book; property documents (hard title or soft "
    "title) to pledge as security; a copy of the business licence; and any other "
    "documents required in particular cases."
),

"product-service-loans-agri-agro-enterprise-credit": (
    "Credit for small, medium and large enterprises in the agricultural chain",
    "This loan is for legal entities or individuals with domestic production "
    "connected to the agricultural and agro-industrial production chain.\n"
    "Requirements: the business, enterprise or company must be registered and "
    "recognised under the law or regulations in force; have a good reputation "
    "and business experience; have clear reports or documents evidencing "
    "business income and expenditure; and have sufficient cash flow to assure "
    "repayment.\n"
    "ARDB lends for seasonal working capital across the production cycle — "
    "supplying agricultural inputs, buying agricultural produce, storage, "
    "drying, processing and packing — and for investment capital for tools, "
    "equipment and machinery, building a factory or production premises, and "
    "other purposes. There are five forms.\n"
    "Short-term working capital: over 20,000 US dollars or the equivalent in "
    "riel, up to 20% of the bank's net own funds, for up to 12 months, at an "
    "interest rate from 7-9% a year. The administrative fee is 1% of the "
    "approved loan amount in the first year and 0.5% of the outstanding balance "
    "in following years, charged annually. Interest is paid monthly and the "
    "principal is amortised monthly, quarterly, half-yearly or yearly, or "
    "according to the business's cash flow.\n"
    "Working capital under a credit ceiling: over 20,000 US dollars or the "
    "equivalent in riel, up to 20% of the bank's net own funds, for up to 24 "
    "months, at an interest rate from 7-9% a year, with an administrative fee of "
    "1% of the loan amount and 0.5% of the outstanding balance in following "
    "years, charged annually. Interest is paid monthly; the principal must be "
    "repaid within 12 months at the latest, and the principal repaid may be "
    "drawn down again for use in the following year.\n"
    "Overdraft: over 20,000 US dollars or the equivalent in riel, up to "
    "1,000,000 US dollars, for up to 12 months, at an interest rate from 7-9% a "
    "year. The administrative fee is 1% of the loan amount and 0.5% of the "
    "outstanding balance in following years, where the loan term is extended or "
    "rolled over. Interest is paid monthly and the principal is repaid at the "
    "end of the term.\n"
    "Long-term investment capital: over 20,000 US dollars or the equivalent in "
    "riel, up to 20% of the bank's net own funds, for up to 84 months, that is 7 "
    "years, at an interest rate from 7-9% a year, with an administrative fee of "
    "1% of the loan amount and 0.5% of the outstanding balance in following "
    "years, charged annually. Interest is paid monthly and the principal is "
    "amortised monthly, quarterly, half-yearly or yearly, or according to the "
    "business's cash flow.\n"
    "Short-term working capital to buy cashew nuts: from 50,000 US dollars or "
    "the equivalent in riel, up to 20% of the bank's net own funds, for no more "
    "than 12 months, at an interest rate from 7-9% a year, with an "
    "administrative fee from 0.5-1% of the loan amount. Interest is paid monthly "
    "and the principal is repaid at the end of the term. Other conditions also "
    "apply.\n"
    "An individual applying needs a copy of the Khmer national identity card and "
    "the family book or residence book; property documents (hard title or soft "
    "title) to pledge as security; a copy of the business licence; and any other "
    "documents required in particular cases.\n"
    "A legal entity needs the Khmer national identity card and the family book "
    "or residence book of its representative; property documents (hard title or "
    "soft title) to pledge as security; financial reports for the previous and "
    "current year; a valid patent certificate and business certificate; a copy "
    "of the articles of association of the company or business unit; and the "
    "board minutes authorising the borrowing from the bank."
),

"product-service-loans-agriculture-community-credit": (
    "Credit for agricultural communities in the agricultural value chain",
    "This loan is for agricultural communities and modern agricultural "
    "communities with domestic production connected to the agricultural and "
    "agro-industrial production chain.\n"
    "Requirements: the community must be registered and recognised by the "
    "supervisory authority and have a clear domestic location or production; "
    "have a good reputation and business experience; keep records and prepare "
    "financial reports as the supervisory authority requires; and have "
    "sufficient cash flow to assure repayment.\n"
    "ARDB lends for seasonal working capital across the production cycle — "
    "supplying agricultural inputs, buying agricultural produce, storage, "
    "drying, processing and packing — and for investment capital for tools, "
    "equipment and machinery, building a factory or production premises, and "
    "other purposes.\n"
    "Short-term working capital: from 5,000 US dollars or the equivalent in riel "
    "up to 1,000,000 US dollars, for up to 36 months, at an interest rate from "
    "7-9% a year, with an administrative fee of 1% of the loan amount charged "
    "once only. Interest is paid monthly and the principal is amortised monthly, "
    "quarterly, half-yearly or yearly, or according to the business's cash "
    "flow.\n"
    "Working capital under a credit ceiling: from 5,000 US dollars or the "
    "equivalent in riel up to 1,000,000 US dollars, for up to 36 months, at an "
    "interest rate from 7-9% a year, with an administrative fee of 1% charged "
    "once only. Interest is paid monthly; the principal must be repaid within 12 "
    "months at the latest, and the principal repaid may be drawn down again for "
    "use in a following year.\n"
    "Long-term investment capital: from 5,000 US dollars or the equivalent in "
    "riel up to 1,000,000 US dollars, for up to 7 years, at an interest rate "
    "from 7-9% a year, with an administrative fee of 1% charged once only, on "
    "the same repayment terms. Other conditions also apply.\n"
    "Documents to apply: a copy of the Khmer national identity card and the "
    "family book or residence book of the representative; property documents "
    "(hard title or soft title) to pledge as security; financial reports for the "
    "previous and current year; the articles of association and the registration "
    "certificate of the agricultural community; and the board minutes "
    "authorising the borrowing from the bank."
),

"product-service-loans-government-agri-credit-program": (
    "Special government programme loan for market intervention",
    "This loan supports a special government programme for market intervention: "
    "development mechanisms and the operation of storage warehouses and dryers "
    "for paddy, maize and other crops. ARDB provides long-term concessional "
    "financing to expand the intervention project of establishing paddy "
    "collection centres, meaning warehouses and dryers, in the private sector at "
    "designated strategic locations, and also provides additional working "
    "capital to buy Sen Kra Ob and Neang Khon fragrant paddy, maize and other "
    "crops.\n"
    "It is aimed at paddy collection centres, rice mills, paddy buyers and "
    "others able to buy fragrant paddy, Neang Khon paddy or other crops from "
    "farmers at prices set by ARDB under the government's direction.\n"
    "Requirements: the business owner, individual or legal entity, must be "
    "registered and recognised by the supervisory authority; have a good "
    "reputation and 2 consecutive years in the paddy and rice sector; warehouse "
    "capacity able to hold at least 3,000 tonnes of paddy; a dryer able to dry "
    "at least 50 tonnes of paddy per day; the stock warehouse sited separately "
    "from the processing mill; sufficient handling equipment in the warehouse, "
    "such as scales, a forklift and a bulldozer; clear reports or documents "
    "evidencing business income and expenditure; and sufficient cash flow to "
    "assure repayment.\n"
    "Short-term working capital: from 50,000 US dollars or the equivalent in "
    "riel, up to 20% of the bank's net own funds, for under 12 months, at an "
    "interest rate of 5% a year. The administrative fee is 1% of the loan amount "
    "for a loan running more than 6 months, and 0.5% of the loan amount for a "
    "loan running less than 6 months. Interest is paid monthly and the principal "
    "is repaid at the end of the term.\n"
    "Long-term investment capital: up to 5,000,000 US dollars or the equivalent "
    "in riel, for up to 10 years, at an interest rate of 5% a year, with an "
    "administrative fee of 1% of the loan amount charged once only, and a grace "
    "period of up to 36 months. Interest is paid monthly and the principal is "
    "amortised monthly, quarterly, half-yearly or yearly, or according to the "
    "business's cash flow. Other conditions also apply.\n"
    "Documents to apply: a copy of the Khmer national identity card and the "
    "family book or residence book; a business licence recognised by the "
    "supervisory authority; a valid patent certificate; a stock declaration "
    "letter for paddy and rice, maize and other stock; and supporting income and "
    "expenditure documents and any other required documents, if applicable."
),

"product-service-loans-loan-wholesale": (
    "Wholesale credit",
    "Wholesale credit is for institutions licensed by the National Bank of "
    "Cambodia: deposit-taking microfinance institutions, microfinance "
    "institutions, rural credit operators and leasing companies. ARDB lends to "
    "them so they can on-lend to their own end customers whose business activity "
    "relates to the agricultural and agro-industrial value chain.\n"
    "Requirements: a licence from the National Bank of Cambodia and compliance "
    "with the requirements of the relevant competent authorities; successful "
    "lending or leasing experience over the last 2 years; a chief executive "
    "and/or chairman of the board with at least 2 years of credit work "
    "experience; a management information system (MIS) and an accounting "
    "management system; minimum capital complying with National Bank of Cambodia "
    "regulations; and a profit in each of the last 2 consecutive years.\n"
    "Short-term working capital: from 100,000 US dollars or the equivalent in "
    "riel, up to 20% of the bank's net own funds, for up to 12 months, at an "
    "interest rate from 7-8% a year. The administrative fee is 1% of the loan "
    "amount in the first year and 0.5% of the outstanding balance after the "
    "first year, charged annually. Interest is paid monthly and the principal is "
    "amortised monthly, quarterly, half-yearly or yearly, or according to the "
    "business's cash flow.\n"
    "Working capital under a credit ceiling: from 100,000 US dollars or the "
    "equivalent in riel, up to 20% of the bank's net own funds, for up to 36 "
    "months, at an interest rate from 7-8% a year, with the same fee structure. "
    "Interest is paid monthly; the principal must be repaid within 12 months, "
    "and the principal repaid may be drawn down again for use in a following "
    "year.\n"
    "Long-term investment capital: from 100,000 US dollars or the equivalent in "
    "riel, up to 20% of the bank's net own funds, for up to 7 years, at an "
    "interest rate from 7-8% a year, with the same fee structure, on the same "
    "repayment terms. Other conditions also apply.\n"
    "Documents to apply: a copy of the Khmer national identity card and the "
    "family book or residence book; property documents (hard title or soft "
    "title) to pledge as security; the licence, articles of association and "
    "business registration certificate for a legal entity; and financial reports "
    "for the last 2 years."
),

"product-service-loans-ardbs-green-loan": (
    "Green loan",
    "The green loan is for individuals or legal entities acting in the "
    "agricultural value chain and serving the rural economy, whose business "
    "activity contributes to protecting the environment and society and to "
    "sustainable national economic development. All applicants must have their "
    "business or production located domestically and must need capital to use in "
    "their own business operations.\n"
    "Green financing covers trades and businesses in the agricultural value "
    "chain, from the start of production through to distribution and "
    "consumption, where the business activity focuses on reducing environmental "
    "impact, adapting to climate change and adopting new technology, and "
    "contributes to rural economic development. It covers four areas. "
    "Mitigation: financing an actor in the agricultural value chain whose "
    "business model helps reduce greenhouse gas emissions or absorbs carbon "
    "dioxide from the atmosphere — for example renewable energy such as solar, "
    "wind, hydroelectric, bioenergy and biogas; improving energy efficiency; "
    "agricultural techniques adapted to reducing carbon emissions; and "
    "regenerative agriculture to maintain soil quality. Adaptation: financing an "
    "actor whose business model supports or reduces vulnerability to climate "
    "change impacts now and in future, for example through climate-resilient "
    "crop varieties able to withstand drought and flood, growing under net "
    "houses or glasshouses, strengthening water management and conservation, and "
    "water-saving irrigation systems. Cross-cutting: financing an actor whose "
    "business model addresses climate change impacts through both mitigation and "
    "adaptation. Co-benefits: every financed trade or investment project must "
    "contribute to the Sustainable Development Goals (SDGs) and deliver at least "
    "one of environmental co-benefits (not causing other environmental harm), "
    "gender and social co-benefits (advancing gender equality and benefits such "
    "as improved human and animal health and safety), or economic co-benefits "
    "(advancing economic sustainability through job creation, higher incomes and "
    "financial inclusion).\n"
    "Requirements: an individual or legal entity with legal personality; a "
    "business in the agricultural value chain; an existing business; a good "
    "credit history; the ability to repay; and property to pledge as security.\n"
    "As working capital: 500 to 100,000 US dollars or the equivalent in riel, at "
    "an interest rate of 6% to 7.5% a year, for up to 12 months.\n"
    "As investment capital: 500 to 200,000 US dollars or the equivalent in riel, "
    "at an interest rate of 6.5% to 7.5% a year, for up to 84 months.\n"
    "On repayment, the principal may be paid monthly, quarterly, half-yearly or "
    "at the end of the term depending on the customer's cash flow, and interest "
    "is paid monthly.\n"
    "Security must be real estate under a title of one of these kinds: a "
    "certificate of property ownership, a certificate of the right to occupy "
    "property, a soft title recognised by a competent institution, or a deposit "
    "certificate.\n"
    "Particular features: repayment flexes with the customer's cash flow; early "
    "repayment carries no penalty; it builds resilience to climate change; the "
    "loan can be used to shift a business from a traditional model to a "
    "sustainable one; it contributes to reducing environmental and social impact "
    "and to increasing climate resilience; and other benefits apply.\n"
    "An individual borrower needs a copy of the Khmer national identity card and "
    "the family book or residence book; property documents (hard title or soft "
    "title) to pledge as security; a copy of the business licence; and any other "
    "documents required in particular cases. A legal entity needs the Khmer "
    "national identity card and family book or residence book of its "
    "representative; property documents to pledge as security; a valid patent "
    "certificate and business certificate; a copy of the articles of association "
    "of the company or business unit; and the minutes of the shareholders' or "
    "leadership meeting resolving to authorise the borrowing from the bank.\n"
    "To apply, contact the nearest ARDB branch or call 098 304 057, 023 220 810 "
    "or 023 220 811."
),

}
