"""English restatements: the bank profile, the two statements, social
responsibility, the informal-economy platform and the ASPIRE-AT project.

ALLOW_MISSING records figures deliberately left out, with the reason. It is
not a way to quieten the checker: every figure not listed there is still
enforced, and anything listed is visible in review rather than silently gone.
"""

ENGLISH = {

"profile": (
    "About ARDB: history, mandate, vision, mission and values",
    "HISTORY. The Rural Development Bank was created by the Royal Government "
    "in 1998 by sub-decree No. 01 ANKr.BK of 21 January 1998, under the name "
    "\"Rural Development Bank (RDB)\", operating as a specialised bank focused on "
    "agriculture. In 2014 the Royal Government issued sub-decree No. 199 "
    "ANKr.BK of 11 June 2014 revising the bank's functions, duties and "
    "structure. The Rural Development Bank then changed from a specialised bank "
    "into a commercial bank and was renamed \"Agricultural and Rural "
    "Development Bank (ARDB)\" by sub-decree No. 124 ANKr.BK of 27 August 2019.\n"
    "The Agricultural and Rural Development Bank, called ARDB Bank, aims to "
    "provide complete, efficient and sustainable banking services in support of "
    "agriculture and the rural economy, contributing to national economic "
    "development in line with the Royal Government's policy.\n"
    "ARDB acts both as a commercial bank and as a policy bank for the Royal "
    "Government: it fills the financing gaps in development projects that "
    "private banks and financial institutions cannot fill. ARDB has been "
    "steadily widening its operations and its capital, and cooperates with many "
    "partners to provide efficient and sustainable financing and banking "
    "services to agriculture. It has brought financial services closer to "
    "customers by extending its network with a branch in Battambang province and "
    "14 mobile offices in the provinces, serving farmers, agricultural "
    "communities, rice mills, small and medium enterprises in agriculture and "
    "agro-industry, and other parties in the agricultural value and production "
    "chain.\n"
    "ROLE AND DUTIES. ARDB sets out its main roles and duties as: acting both "
    "as a commercial bank and as a policy bank; providing financing and related "
    "banking services, including credit, payment and deposit-taking services, to "
    "target customers in the agricultural production chain and the rural "
    "economy; providing policy support on financial and technical matters, "
    "including coordination and problem-solving in the production chain, "
    "agriculture and the rural economy, through finding markets, giving advice "
    "and building capacity; promoting the use of technology and innovation to "
    "strengthen the efficiency of its services and improve its customers' "
    "competitive advantage in the market; cooperating and entering joint "
    "arrangements with national and international financial institutions to "
    "provide financing or implement projects related to agriculture and the "
    "rural economy; implementing financing projects or managing other funds "
    "within frameworks of cooperation with development partners and the private "
    "sector; managing the Royal Government's intervention programmes and "
    "projects; mobilising capital and financing to expand ARDB's activities; "
    "providing other banking services connected with managing and allocating "
    "financial resources efficiently for target customers, while holding to the "
    "principles of good governance and social and environmental responsibility; "
    "and cooperating with the relevant ministries and institutions so that "
    "ARDB's roles and duties are carried out effectively.\n"
    "VISION. The Agricultural and Rural Development Bank is a leading green and "
    "sustainable financing institution focused on developing agriculture, the "
    "rural sector and the green sector in the Asia-Pacific region.\n"
    "MISSION. Developing strong and sustainable relationships with every actor "
    "in the agricultural production value chain, rural development and the green "
    "sector, through complete and inclusive financial services. Identifying, "
    "coordinating and closing market gaps in agriculture, rural development and "
    "the green sector, through strategic partnerships and financial solutions "
    "that use technology, green financing and sustainable financing. "
    "Diversifying the rural economy by providing green and sustainable financing "
    "services to small and medium enterprises in rural development. Promoting "
    "sustainable saving in rural development, and financial literacy.\n"
    "GOALS. Transforming the bank into a fully digital bank providing green and "
    "sustainable financing through the use of artificial intelligence. Turning "
    "farmers into farmer-entrepreneurs through technical assistance and raising "
    "awareness, in order to promote exports and help safeguard Cambodia's food "
    "security. Promoting clusters of micro, small and medium enterprises for "
    "agro-industrial business, with the aim of building a sustainable "
    "agricultural production value chain. Promoting the green sector and "
    "resilience to climate change through green and sustainable financing.\n"
    "CORE VALUES. Integrity, a core value linking honesty and professional "
    "conscience. Cooperation, a core value expressing communication and working "
    "together to reach a shared goal. Innovation, a core value expressing work "
    "carried out in a modern and creative way."
),

"profile-boards-statement": (
    "Statement of the board of directors",
    "A statement from the Chairman of the Board of Directors.\n"
    "2021 was a year in which the whole world, Cambodia among it, was working to "
    "restore economic and social conditions to normal and trying to live along a "
    "new path. The COVID-19 crisis certainly had a negative effect on Cambodia's "
    "economic and social situation, but it did not halt the Royal Government of "
    "Cambodia's efforts to drive the development of agriculture. On the "
    "contrary, the crisis created opportunities for developing agriculture in "
    "Cambodia, both in the scale of investment in agricultural land and in "
    "cultivation techniques. ARDB, as an arm of the Ministry of Economy and "
    "Finance, is implementing the post-COVID economic recovery policy with the "
    "greatest care, through the release of special financing. As a result ARDB "
    "released this special financing fund, which covered the expansion of "
    "vegetable and fruit growing, aquaculture, animal raising and the processing "
    "of agricultural products; and the Royal Government continues to give its "
    "attention and support to priority sectors, agriculture among them. The "
    "Royal Government's special financing policy, carried out in 2020 and 2021, "
    "had strong support from farmers, agricultural communities and small and "
    "medium enterprises in agriculture.\n"
    "In line with the strategic framework and the programme to recover and drive "
    "the growth of Cambodia's economy while living with COVID-19 along the new "
    "normal path for 2021-2023, ARDB continues to carry out the Royal "
    "Government's policy attentively and to follow its 3-year rolling business "
    "plan (2022-2024) in order to reach the bank's goals.\n"
    "As Chairman of the Board of Directors of ARDB, I commend and thank the "
    "members of the board, the leadership and the staff at every level of ARDB, "
    "who have worked hard and actively at their duties in carrying out the Royal "
    "Government's policy and fulfilling the bank's mission, towards the shared "
    "goal: for farmers, and for social and economic development."
),

"profile-ceos-statement": (
    "Statement of the Director General",
    "A statement from the Director General.\n"
    "Although in 2021 the COVID-19 crisis continued to affect the global economy "
    "and Cambodia's economy, ARDB continued to play its part well in carrying "
    "out the Royal Government's policy, in particular in delivering the Royal "
    "Government's special financing to restore and steady the businesses of "
    "farmers, agricultural communities and small and medium enterprises in "
    "agriculture. In 2021 ARDB achieved a number of significant results: (1) the "
    "total loan portfolio rose to 302 million US dollars, a growth of 21.75% "
    "against 2020; (2) the number of deposit accounts grew by 73%, a growth "
    "arising from the growth in savings deposit accounts and fixed deposit "
    "accounts, with the fixed deposit balance growing by 118.29%; (3) the launch "
    "of the trade finance service, which helps ease and drive the export of "
    "Cambodia's agricultural products; (4) the extension of the mobile office "
    "network to 10 provinces: Battambang, Banteay Meanchey, Oddar Meanchey, "
    "Pursat, Kampong Thom, Preah Vihear, Prey Veng, Tbong Khmum, Takeo and Stung "
    "Treng; and (5) closer cooperation with national institutions and "
    "development partners, with the aim of widening the reach of its financing "
    "and contributing to the sustainable development goals.\n"
    "OUTLOOK FOR 2022. Based on ARDB's 10-year roadmap and the continued "
    "implementation of the Royal Government's policy of driving agriculture "
    "forward, with the aim of raising farmers' living standards and developing "
    "the economy and society, ARDB has set out its way forward clearly in its "
    "main business plans for the coming year 2022: (1) driving the efficiency "
    "with which the Royal Government's policy is carried out, and closer "
    "cooperation with national and international development partners; (2) "
    "driving the transformation of farmers into farmer-entrepreneurs; (3) "
    "driving the transformation into a digital bank, in both operations and "
    "customer service; (4) driving the diversification of funding sources and "
    "the practice of green credit; (5) driving deposit-taking and increasing and "
    "diversifying the loan portfolio; and (6) driving productivity and "
    "professional working practice through developing the capacity of human "
    "resources.\n"
    "I take this occasion to express my respect and deep gratitude to the Royal "
    "Government of Cambodia, the Ministry of Economy and Finance and the "
    "National Bank of Cambodia, which have always supported ARDB and placed "
    "their trust in it. I also thank the board of directors and the leadership, "
    "who have always supported ARDB and given it good counsel; all the bank's "
    "staff, who have worked with all their strength of body and mind; and the "
    "customers and development partners who have cooperated with ARDB in "
    "advancing the development of agriculture in Cambodia."
),

"profile-socialresponse": (
    "ARDB social responsibility activities",
    "ARDB publishes a list of its social responsibility activities.\n"
    "ARDB held a ceremony to sign a memorandum of understanding on the use of "
    "the services of the Agricultural and Rural Development Bank, for gathering "
    "and receiving charitable contributions for the Kantha Bopha Foundation "
    "Cambodia, between the Kantha Bopha Foundation Cambodia and the Agricultural "
    "and Rural Development Bank.\n"
    "13 May 2022: a working group representing His Excellency Kao Thach, "
    "Delegate of the Royal Government in charge of the role of Director General "
    "of ARDB, brought a valued gift to a young boy named Kong Seiha.\n"
    "4 November 2021: His Excellency Kao Thach, Director General of the Rural "
    "Development Bank, and the Khmer Hamilton-Phnom Penh Association visited "
    "orphaned children of the Future Light Organisation.\n"
    "10 November 2020: a working group of the Rural Development Bank, "
    "representing His Excellency Kao Thach, Director General of the Rural "
    "Development Bank, brought 1 tonne of rice to support an organisation for "
    "the development of children and poor communities.\n"
    "10 November 2020: the Director General of the Agricultural and Rural "
    "Development Bank attended the inauguration of a library and a fence at Hun "
    "Sen Prey Totoeng High School.\n"
    "10 November 2020: a final football match was held between the youth team of "
    "the Union of Youth Federations of Cambodia at Peam Oknha Ung High School "
    "and the youth team of the Union of Youth Federations of Cambodia of Thmar "
    "Kor Commune, for the Union of Youth Federations of Cambodia trophy of Lvea "
    "Em District, under the presidency of His Excellency Kao Thach, Director "
    "General of the Rural Development Bank.\n"
    "10 November 2020: Mr Bun Pheng, Governor of the Board of Governors of "
    "Khsach Kandal District, and colleagues attended a discussion event with "
    "grade 12 students preparing to sit the general upper secondary school "
    "diploma examination.\n"
    "10 November 2020: His Excellency Kao Thach, Director General of the Rural "
    "Development Bank, as the high representative of His Excellency Academician "
    "Aun Pornmoniroth, attended a discussion event with grade 12 students.\n"
    "10 November 2020: His Excellency Kao Thach, Director General of the Rural "
    "Development Bank and head of the Cambodian youth movement working group for "
    "Khsach Kandal District, as the high representative of His Excellency "
    "Academician Aun Pornmoniroth, visited Kandal province to help.\n"
    "10 November 2020: a lottery event to select scholarship recipients and hand "
    "over the scholarships of His Excellency Academician Aun Pornmoniroth, "
    "Deputy Prime Minister, Minister of Economy and Finance and head of the "
    "central-level working group assisting Kandal province.\n"
    "10 November 2020: the Rural Development Bank visited Mr Kong So, head of "
    "the dry-season rice association of Lvea Em District, to ask after his "
    "injury, after he lost a finger of his left hand in an accident while drying "
    "community members' rice.\n"
    "10 November 2020: the Rural Development Bank contributed funds towards "
    "printing 1,000 copies of the book Hun Sen Cambodia and the book Outstanding "
    "Women, Former Farmers of Cambodia."
),

"product-service-services-digital-platform-for-informal-econo": (
    "Registration of informal economy workers (Cam-IE digital platform)",
    "WHAT IS THE DIGITAL PLATFORM FOR INFORMAL ECONOMY DEVELOPMENT? It is a "
    "platform on which people in the informal economy can register in order to "
    "obtain the status of an informal economy worker, recognised by the Royal "
    "Government. Using the data obtained through this registration, the Royal "
    "Government will prepare a package of benefits answering the needs of "
    "informal economy workers.\n"
    "WHO CAN REGISTER AS AN INFORMAL ECONOMY WORKER? Employees of micro "
    "enterprises, meaning people of any sex who have entered a contract to work "
    "for payment under the direction and management of another person, whether a "
    "natural person or a public or private legal person. Casual employees, "
    "meaning people who have entered a contract for a definite piece of work, "
    "normally to be completed within a short period, working occasionally, "
    "intermittently or seasonally. A micro enterprise means a business "
    "enterprise of any kind with an annual turnover below 62,250 US dollars, or "
    "with fewer than 5 employees. Self-employed persons, meaning people who "
    "carry on work or an occupation earning their own income, not involving "
    "wages or a salary provided by an employer or the state under an employment "
    "contract, and who do not employ workers in their work or occupation.\n"
    "THE MAIN DOCUMENTS REQUIRED: the original Khmer national identity card; a "
    "photograph of the face; a photograph of the face together with the business "
    "location; and photographs of the business activity.\n"
    "HOW TO REGISTER THROUGH THE DIGITAL PLATFORM FOR INFORMAL ECONOMY "
    "DEVELOPMENT (Cam-IE). Open the Cam-IE application. Fill in the information "
    "to create a new user account: enter a telephone number, create a password "
    "and confirm the password. The password must have at least 6 characters and "
    "must contain a lower-case letter, an upper-case letter and a number. Then "
    "tick the box and press \"create new account\". Enter the 6-digit code sent "
    "to the telephone number and press the \"verify\" button.\n"
    "Upload a photograph of the Khmer national identity card, photographed or "
    "scanned from the original, in PNG, JPG or JPEG format. Place a photograph "
    "of your face inside the picture frame. Masks, hats and glasses are not "
    "allowed.\n"
    "Check the information filled in automatically from the original identity "
    "card, correct it so that it is right, and press \"next\".\n"
    "Then fill in the information the system asks for: education, health and "
    "family information; information on the business, occupation or work; the "
    "support needed from the Royal Government; and a photograph of the face "
    "together with the business location and photographs of the business "
    "activity. Then press the \"save\" button.\n"
    "Press the \"add\" button if there is another business, occupation or work "
    "in the informal economy, then press the \"next\" button.\n"
    "Check the information, then tick the box and press the \"register\" button.\n"
    "After registration there will be a review and a reply within at most 1 "
    "working day. If approved, the informal economy worker will receive a "
    "certificate of registration as an informal economy worker."
),

"ardb-project-agriculture-services-program-for-an-inclusive-r": (
    "ASPIRE-AT: Agriculture Services Programme for an Inclusive Rural Economy "
    "and Agricultural Trade",
    "ABOUT THE PROJECT. The Agriculture Services Programme for an Inclusive "
    "Rural Economy and Agricultural Trade (ASPIRE-AT) is a programme of the "
    "Royal Government of the Kingdom of Cambodia (GoKC), the implementation of "
    "which is managed by the Ministry of Agriculture, Forestry and Fisheries. "
    "The programme is financed by loans from the International Fund for "
    "Agricultural Development (IFAD) and the European Investment Bank (EIB), and "
    "by the Royal Government of Cambodia.\n"
    "ASPIRE-AT aims to develop agriculture inclusively and sustainably by "
    "driving domestic and export markets, which helps raise the incomes of "
    "farmers and rural workers.\n"
    "ARDB has been selected as the financial institution providing credit and "
    "grants to the project's beneficiaries, supporting 7 target agricultural "
    "product value chains: free-range chicken, vegetables, maize, cashew nuts, "
    "pepper, fresh fruit and processed fruit for export.\n"
    "The programme runs for 7 years, from 2023 to 2029, and is carried out in 21 "
    "target provinces: Battambang, Pailin, Banteay Meanchey, Siem Reap, Kampong "
    "Cham, Kampong Thom, Kratie, Tbong Khmum, Preah Vihear, Ratanakiri, Stung "
    "Treng, Oddar Meanchey, Kampong Speu, Kampot, Preah Sihanouk, Kampong "
    "Chhnang, Pursat, Kandal, Takeo, Svay Rieng and Prey Veng.\n"
    "ARDB'S ROLE IN ASPIRE-AT. ARDB has been selected as the financial "
    "institution providing loans to the project's beneficiaries and managing the "
    "grants.\n"
    "Project funds: the credit fund is 7.9 million US dollars and the grants are "
    "2.5 million US dollars. Project implementation period: 2023-2029. "
    "Beneficiaries: producer organisations (POs) and/or agricultural communities "
    "(AC) whose members are small-scale farmers. Target provinces: Battambang, "
    "Pailin, Banteay Meanchey, Siem Reap, Kampong Cham, Kampong Thom, Kratie, "
    "Tbong Khmum, Preah Vihear, Ratanakiri, Stung Treng, Oddar Meanchey, Kampong "
    "Speu, Kampot, Preah Sihanouk, Kampong Chhnang, Pursat, Kandal, Takeo, Svay "
    "Rieng and Prey Veng. Agricultural products: free-range chicken, vegetables, "
    "maize, cashew nuts, pepper, fresh fruit and processed fruit for export.\n"
    "CONDITIONS REQUIRED: having legal personality; having business experience; "
    "having a good record in the use of credit; and having the ability to repay.\n"
    "DOCUMENTS REQUIRED: Khmer national identity card and family book or "
    "residence book (copies); business permit (copy); documents confirming "
    "income and expenditure information, and a business plan; and other "
    "documents required in case of need.\n"
    "FEATURES OF THE CREDIT PRODUCT. Description: investment capital. Loan size: "
    "from 500 US dollars up to 200,000 US dollars. Interest rate: 8% a year. "
    "Term: up to 84 months.\n"
    "REPAYMENT METHOD. The principal may be paid monthly, quarterly, "
    "half-yearly or at the end of the term, depending on the customer's cash "
    "flow. Interest must be paid monthly.\n"
    "HOW TO APPLY. Please contact the Agricultural and Rural Development Bank "
    "nearest to you, or telephone 098 304 057 / 023 220 810 / 811."
),

}

#: Figures deliberately omitted, with the reason. Everything else is enforced.
ALLOW_MISSING = {}
