"""English restatements: the FAQ and the remaining profile pages."""

FAQ = (
    "ARDB frequently asked questions",
    "WHAT ARDB IS. The Agricultural and Rural Development Bank (ARDB) is a "
    "state bank established by the Royal Government of Cambodia in 1998 to fill "
    "the gap between demand for and supply of financial services in rural areas, "
    "and so help reduce poverty among the Cambodian people. In 2019 the Rural "
    "Development Bank became the Agricultural and Rural Development Bank (ARDB) "
    "by sub-decree number 124 ANKr.BK dated 27 August 2019. ARDB is designated a "
    "public enterprise in the form of a state company and a commercial bank, "
    "with full autonomy in directing and managing its own activities. It is "
    "under the technical and financial supervision of the Ministry of Economy "
    "and Finance and under the oversight of the National Bank of Cambodia.\n"
    "VISION. ARDB's vision is to be a leading financial institution focused on "
    "developing the agricultural and rural sectors in Cambodia.\n"
    "CORE VALUES. Integrity, which links honesty with professional conscience; "
    "cooperation, which is communicating and working together to reach shared "
    "goals; and innovation, which is working in a modern and creative way.\n"
    "ARDB's credit products are: credit under the government's special financing "
    "programme supporting handicraft businesses and small and medium enterprises "
    "in agricultural processing, agro-industry and agriculture (SMAEs); credit "
    "for small, medium and large enterprises in agriculture (SME); agricultural "
    "community credit (Agricultural Cooperative); credit to support small-scale "
    "agriculture (Small Loan); credit supporting the Agricultural Inclusive "
    "Market Support project (AIMS); AIMS credit accepting a paddy purchase and "
    "sale payment agreement as debt security (2023); wholesale credit (Wholesale "
    "Loan); the special government programme loan for market intervention "
    "covering development mechanisms and the operation of storage warehouses and "
    "paddy dryers and the purchase of paddy, maize or other crops; credit for "
    "working capital to buy paddy under the former Agricultural Sector "
    "Development Fund (ASDF); credit under the government's special financing "
    "programme for agricultural SMEs (SME-Agri); credit under the Smart "
    "Agriculture project supporting safe vegetable growing and domestic safe "
    "vegetable supply (Smart Agriculture); credit under the credit fund of the "
    "Cambodia Agricultural Sector Diversification Project (CASDP); credit under "
    "the Agricultural Value Chain Competitiveness and Safety Enhancement Project "
    "(ACSEP); the special loan under the 100 million US dollar financing "
    "programme to raise agricultural production, find markets and stabilise crop "
    "prices (for the rice sector, 2024); credit for women entrepreneurs in the "
    "agricultural and agro-industrial production chain (AVCL); and the green "
    "loan.\n"

    "SMAEs — GOVERNMENT SPECIAL FINANCING PROGRAMME. Open to growers and "
    "producers, farm owners, agricultural communities, handicraft businesses and "
    "small and medium enterprises needing capital to expand: growing vegetables "
    "and fruit; raising livestock such as chickens, ducks, pigs and cattle; "
    "aquaculture such as fish, frogs, eels and prawns; and processing "
    "agro-industrial products and food. Working capital means buying and "
    "processing agricultural produce, growing vegetables and fruit, raising "
    "livestock and aquaculture. Investment capital means buying tools, equipment "
    "and machinery, building a factory, shed or production building connected to "
    "producing or processing agricultural, agro-industrial, aquaculture and food "
    "products, or buying agricultural technology. Working capital runs from 5,000 "
    "up to 200,000 US dollars or the riel equivalent; investment capital from "
    "5,000 up to 300,000 US dollars or the riel equivalent. Working capital runs "
    "2 years or less and investment capital 7 years or less. The working capital "
    "rate is 5% a year, or for riel an additional 0.5% a year; the investment "
    "rate is 5.5% a year, or for riel an additional 0.5% a year. Interest is "
    "paid monthly; the principal may be paid monthly, quarterly, half-yearly or "
    "yearly based on cash flow, after any grace period or with none. Conditions: "
    "an existing business operating well for at least two years; security for "
    "the debt, being real estate, other guarantee letters or a deposit "
    "certificate; a business licence and other legal documents; and the ability "
    "to repay. Features: early repayment of principal without penalty; a grace "
    "period on principal for the first 1 year on investment capital; and a low "
    "interest rate for the agricultural sector.\n"

    "SME — SMALL, MEDIUM AND LARGE ENTERPRISES IN THE AGRICULTURAL VALUE CHAIN. "
    "Open to legal entities or individuals in the chain, or with a business or "
    "production related to agriculture, including producing, processing, storing, "
    "distributing and exporting agricultural products, especially in the paddy "
    "and rice sector, and other areas tied to social and economic development. "
    "For small and medium enterprises the loan runs from 20,000 US dollars to "
    "1,000,000 US dollars or the riel equivalent; for large enterprises, over "
    "1,000,000 US dollars. A short-term loan runs 3 years or less and a long-term "
    "loan 7 years or less. The rate is 7% to 9% a year on US dollar loans, or for "
    "riel an additional 0.5% a year. Interest is paid monthly; a grace period of "
    "the first 1 year on principal may be available; the principal may be paid "
    "monthly, quarterly, half-yearly or yearly based on cash flow, after any "
    "grace period or with none. Conditions: the business owner, individual or "
    "legal entity, registered and recognised under the law or regulations in "
    "force; a successful business over 2 consecutive years, confirmed by a site "
    "visit; own or shareholder capital of at least 20% of the value of the "
    "business project; security for the debt, being real estate, other guarantee "
    "letters, a deposit certificate, a government bond or stock; the ability to "
    "repay; and debt against total assets not exceeding 50%. Features: early "
    "repayment of principal without penalty; a grace period on principal for the "
    "first 1 year on investment capital; and a low interest rate for the "
    "agricultural sector.\n"

    "AGRICULTURAL COMMUNITY CREDIT. Open to an agricultural community registered "
    "and recognised by the supervisory authority, with a clear business direction "
    "and purpose that serves the shared interests of its members. Working capital "
    "runs from 5,000 US dollars to 100,000 US dollars or the riel equivalent; "
    "investment capital from 5,000 US dollars to 200,000 US dollars or the riel "
    "equivalent. Working capital runs 3 years or less and investment capital 7 "
    "years or less. The working capital rate is 10.5% for US dollars, or for riel "
    "an additional 0.5% a year; the investment rate is 9.5% for US dollars, or "
    "for riel an additional 0.5% a year. Interest is paid monthly or quarterly; "
    "the principal may be paid monthly, quarterly, half-yearly or yearly based on "
    "cash flow. Conditions: a valid certificate of registration as an "
    "agricultural community; at least 1 year of business experience; security for "
    "the debt; the ability to repay; and debt against total assets not exceeding "
    "50%. Features: early repayment of principal without penalty, and a low "
    "interest rate for the agricultural sector.\n"

    "SMALL LOAN — SUPPORT FOR SMALL-SCALE AGRICULTURE. Open to individuals of "
    "Khmer nationality working in a trade related to agriculture, with a clear "
    "place of residence or work and a good record. The loan runs from 500 up to "
    "20,000 US dollars or the riel equivalent, for up to 36 months as working "
    "capital and up to 60 months as investment capital, at 8% to 11% a year in US "
    "dollars or the riel equivalent. Interest is paid monthly; the principal may "
    "be paid monthly, quarterly, half-yearly or yearly based on cash flow. "
    "Conditions: Khmer nationality; a clear place of residence or work and a good "
    "record; and relevant experience in the trade or business. Features: early "
    "repayment of principal without penalty, and a low interest rate for the "
    "agricultural sector.\n"

    "AIMS — AGRICULTURAL INCLUSIVE MARKET SUPPORT PROJECT. Open to individuals or "
    "legal entities within the AIMS project who are part of, or whose activity "
    "relates to, the agricultural production chains of vegetables, free-range "
    "chicken, cassava, paddy and raw silk. The loan starts from 500 US dollars "
    "and runs up to 36 months as working capital and up to 60 months as "
    "investment capital, at 7% a year for US dollars, or for riel an additional "
    "1.5% a year. Interest is paid monthly; the principal may be paid monthly, "
    "quarterly, half-yearly or yearly based on the customer's cash flow. "
    "Conditions: an existing business; membership of the AIMS project; security "
    "for the debt; and the ability to repay. Features: early repayment of "
    "principal without penalty; other benefits from the AIMS project such as "
    "production chain support and market linkage between producers and buyers; "
    "and a low interest rate for the agricultural sector.\n"

    "WHOLESALE LOAN. Open to deposit-taking microfinance institutions, "
    "microfinance institutions, rural credit operators and financial leasing "
    "companies licensed by the National Bank of Cambodia and meeting the "
    "requirements of the relevant competent authorities. The loan starts from "
    "100,000 US dollars or the riel equivalent. A long-term loan runs more than "
    "12 months; a short-term loan up to 36 months. The rate is 7% to 8% a year "
    "for US dollars, and for riel an additional 0.5% a year. Interest is paid "
    "monthly or periodically; the principal may be paid at maturity or amortised "
    "down based on cash flow. Conditions: the licence and compliance described "
    "above; successful lending or financial leasing experience over 2 consecutive "
    "years; audited financial reports for the past 2 years; a business plan for "
    "the 3 years ahead; security for the debt; and the ability to repay. "
    "Features: early repayment of principal without penalty, and a low interest "
    "rate for the agricultural sector.\n"

    "SPECIAL GOVERNMENT PROGRAMME — WAREHOUSES AND DRYERS. Open to paddy "
    "collection centres, rice mills, paddy buyers and others able to buy fragrant "
    "paddy, Neang Khon paddy or other crops from farmers at prices set by ARDB "
    "under the government's direction. A short-term loan and an overdraft run "
    "from 50,000 US dollars to 20% of the bank's net own funds, or the riel "
    "equivalent; a long-term loan may be up to 5,000,000 US dollars or the riel "
    "equivalent, or as the project requires. The short-term loan and overdraft "
    "run 1 year or less; the long-term loan 10 years or less. The rate on the "
    "long-term loan, the short-term loan and the overdraft is 5% a year for US "
    "dollars and riel. Interest is paid monthly; the principal is repaid when the "
    "paddy, rice or maize stock is withdrawn from the warehouse securing it, or "
    "at the principal's maturity. Conditions for working capital: the business "
    "owner, individual or legal entity, registered and recognised by law or by "
    "the supervisory authority; storage and drying capacity, with a warehouse "
    "able to store at least 3,000 tonnes of paddy and drying capacity of 50 "
    "tonnes a day; and a good reputation with 2 consecutive years in the paddy "
    "and rice sector. Conditions for investment capital: documents of company "
    "registration or a licence conferring the right to trade and export; at least "
    "5 years of experience in the paddy and rice sector or similar agriculture, "
    "with evidence of successful operations and of activities related to "
    "agricultural contracts or other methods; and land of suitable size to build "
    "a paddy and rice warehouse with capacity for 50,000 tonnes and a dryer able "
    "to dry 500-1,000 tonnes a day, on a building area of between 3 hectares and "
    "4 hectares, including a plan to expand the rice mill. Features: early "
    "repayment of principal without penalty; a loan term of 10 years on "
    "investment capital; and a grace period on principal of up to 3 years on "
    "investment capital.\n"

    "ASDF — WORKING CAPITAL TO BUY PADDY. Open to paddy collection centres, rice "
    "mills, paddy and rice milling, processing and exporting companies, and buyers "
    "or owners of other crop silos willing and able to buy paddy from farmers at "
    "a price appropriate to the market. The loan may not exceed 4 times the "
    "applicant's own capital and may not exceed 20% of ARDB's capital. A "
    "short-term working capital loan runs up to 3 years. The rate is 5% a year in "
    "US dollars, or for riel an additional 0.5% a year, or a rate set by the "
    "board of directors. Interest is paid monthly; the principal may be paid at "
    "maturity or amortised based on cash movement. Conditions: an individual or "
    "legal entity registered and recognised under the law or regulations in "
    "force; an existing business operating well for at least two years; security "
    "for the debt, being real estate, stock, other guarantee letters or a deposit "
    "certificate; a business licence and other legal documents; and the ability "
    "to repay. Features: early repayment of principal without penalty, and a low "
    "interest rate for the agricultural sector.\n"

    "SME-AGRI — GOVERNMENT SPECIAL FINANCING PROGRAMME. Open to business and "
    "enterprise owners or companies, agricultural communities, growers and "
    "producers needing capital to expand in cashew, mango, Pailin longan, raising "
    "livestock, aquaculture, vegetables and fruit, cassava, paddy and rice, "
    "processing agricultural and agro-industrial products, and supplying "
    "agricultural inputs. Working capital here means capital for supplying "
    "agricultural inputs, growing, buying, storage, drying, processing, packing "
    "and exporting. Investment capital means capital invested in growing or "
    "raising livestock, tools, equipment and heavy machinery, building a factory "
    "or production building, expanding warehouse capacity, and installing "
    "technology connected to those activities. Working capital starts from 50,000 "
    "US dollars or the riel equivalent where cashew stock and/or a payment "
    "guarantee letter from the buyer is taken as security; working capital starts "
    "from 5,000 US dollars or the riel equivalent where land and buildings are "
    "taken as security; investment capital starts from 5,000 US dollars or the "
    "riel equivalent. Working capital secured on cashew stock or a buyer's "
    "guarantee runs no more than 12 months; other working capital runs 2 years or "
    "less; investment capital runs 7 years or less. The working capital rate is "
    "6% a year for US dollars and riel; the investment rate is 6.5% a year for US "
    "dollars and riel. Interest is paid monthly; the principal on working capital "
    "may be paid at the end of the term or period, and on investment capital "
    "monthly, quarterly, half-yearly or yearly based on cash flow after any grace "
    "period or with none. Conditions: experience with an existing business "
    "operating well; security for the debt; for working capital secured on stock, "
    "a cashew drying silo of at least 5 tonnes a day and storage of at least 200 "
    "tonnes, with suitable technical equipment and machinery for the cashew "
    "buying business; a business licence and other legal documents; and the "
    "ability to repay. Features: early repayment of principal without penalty; a "
    "grace period on principal for the first 2 years on investment capital; and a "
    "low interest rate for the agricultural sector.\n"

    "SMART AGRICULTURE. The Smart Agriculture project was created by ARDB itself. "
    "It focuses on producing safe vegetables in net houses to correct technique "
    "and good quality while assuring a reasonable market price, to support poor "
    "farmers who grow vegetables, vegetable buyers, students and other growers, "
    "through relaxed conditions, a reasonably low interest rate and high "
    "flexibility. It runs in 3 pilot target provinces: Kandal, Kampong Chhnang "
    "and Pailin. The loan runs up to 14,540 US dollars for 4 net houses, or more "
    "than that for other growers in the project. It runs no more than 5 years at "
    "5.5% a year for dollars. Interest payment can be flexible, or interest may "
    "be accrued for the first 6 months; principal payment can be flexible, or "
    "principal may be accrued for the first 6 months; and the principal may be "
    "paid monthly, quarterly, half-yearly or yearly. Conditions: a low-income "
    "household, or a student with relevant skills or recently graduated with a "
    "bachelor's degree in agriculture, or another grower, with a strong "
    "willingness to take part in the project; the ability to reside there, or a "
    "land lease contract from the Smart Agriculture project to build the safe "
    "vegetable net house; the safe vegetable net house and equipment under the "
    "Smart Agriculture credit project at the project site serve as the security "
    "for the debt; and acceptance of training in growing technique as the project "
    "requires. Features: early repayment of principal without penalty; a site "
    "already available for building the net house; a clear growing plan by stage "
    "or cycle; support from ARDB with high flexibility; and a low interest rate "
    "for the agricultural sector.\n"

    "CASDP — CAMBODIA AGRICULTURAL SECTOR DIVERSIFICATION PROJECT. ARDB acts as "
    "the treasury bank implementing CASDP, lending wholesale to 3 participating "
    "financial institutions: Cambodia Post Bank Plc, AMK Microfinance Institution "
    "Plc, and Chamroeun Microfinance Plc. Those three on-lend to customers who "
    "are agribusiness enterprises, agricultural communities, individuals and "
    "other actors in the agricultural production chain, excluding paddy and rice, "
    "located in 13 target provinces: Kampong Cham, Kampong Speu, Battambang, "
    "Kampong Chhnang, Kandal, Kratie, Mondulkiri, Ratanakiri, Preah Vihear, Siem "
    "Reap, Stung Treng, Tbong Khmum and Phnom Penh. Working capital runs up to "
    "250,000 US dollars; investment capital up to 400,000 US dollars, or up to "
    "1,000,000 US dollars for a whole value chain. Working capital runs no more "
    "than 18 months; investment capital no more than 96 months or 120 months, "
    "depending on assessment. The interest rate on both working and investment "
    "capital is set by the 3 financial institutions. Interest is paid monthly; "
    "the principal may be paid monthly, quarterly, half-yearly or yearly based on "
    "cash flow. Conditions: experience with an existing business operating well; "
    "security for the debt; a business licence and other legal documents as the 3 "
    "financial institutions require; and the ability to repay. Features: support "
    "from the CASDP project, and technical training or other workshops as the "
    "project arranges.\n"

    "ACSEP — AGRICULTURAL VALUE CHAIN COMPETITIVENESS AND SAFETY ENHANCEMENT "
    "PROJECT. Open to business and enterprise owners, agricultural communities "
    "and their members, growers, and producers or processors needing capital to "
    "expand in 5 agricultural production chains: vegetables, local chicken, "
    "cashew, cassava and mango, in 6 target provinces: Tbong Khmum, Kampong Cham, "
    "Kampong Thom, Preah Vihear, Siem Reap and Oddar Meanchey. An agricultural "
    "production loan runs up to 150,000 US dollars or the riel equivalent, from 3 "
    "months to 36 months, at 7% a year. A stock procurement loan or seasonal "
    "credit line for working capital runs up to 300,000 US dollars or the riel "
    "equivalent, from 3 months to 6 months, at 7% a year. A short to medium term "
    "small business loan for working capital and equipment runs up to 200,000 US "
    "dollars or the riel equivalent, from 12 months to 48 months, at 7% a year. A "
    "term loan for long-term capital investment and for working capital runs up "
    "to 1,500,000 US dollars or the riel equivalent, from 48 months to 120 "
    "months, at 7% a year. Interest is paid monthly; the principal may be paid "
    "monthly, quarterly, half-yearly or yearly based on cash flow. Conditions: "
    "experience with an existing business operating well; an individual or legal "
    "entity registered and recognised under the law or regulations in force; "
    "security for the debt, which may be real estate, other guarantee letters or "
    "a deposit certificate, or a credit guarantee from the Credit Guarantee "
    "Corporation of Cambodia (CGCC) where there is no collateral; a business "
    "licence and other legal documents; the ability to repay; and an assurance "
    "that the business activity has no negative environmental or social impact. "
    "Features: early repayment of principal without penalty; support from the "
    "ACSEP project; technical training or other workshops as the project "
    "arranges; and a low interest rate for the agricultural sector.\n"

    "100 MILLION US DOLLAR PROGRAMME (RICE SECTOR, 2024). Open to rice mills, "
    "paddy and rice milling and rice exporting companies, paddy and rice "
    "collection centres, and other buyers or owners of paddy and rice warehouses "
    "and dryers willing and able to buy paddy at market prices and/or at another "
    "suitable set price. Working capital may be provided up to 80% of the paddy "
    "and rice stock held in the warehouse, as a loan secured on that stock. It "
    "runs no more than 6 months at 4% a year for US dollars and/or riel. Interest "
    "is paid monthly and the principal is repaid at the end of the term or "
    "period. Conditions: experience with an existing business operating well; the "
    "business owner a legal entity and a member of the Cambodia Rice Federation, "
    "registered and recognised by law; paddy and rice stock held in the warehouse "
    "to secure the loan applied for; a paddy and rice warehouse able to store at "
    "least 3,000 tonnes and a paddy dryer able to dry at least 50 tonnes a day, "
    "meeting correct technical standards; a network connection with farmers or "
    "agricultural communities for buying paddy at a suitable price; other legal "
    "documents supporting the business where required; and the ability to repay. "
    "Features: early repayment of principal without penalty; no requirement for "
    "real estate such as a house or land as debt security; and a low interest "
    "rate for the agricultural sector.\n"

    "AVCL — WOMEN ENTREPRENEURS. Open to women entrepreneurs in the agricultural "
    "and agro-industrial production chain meeting 02 of the following 04 "
    "criteria: the business owner or the owner's representative is a woman, "
    "through the business registration; most shareholders are women; most of the "
    "business's working staff are women; or most members of the board or the "
    "management team are women. Working capital here means capital for supplying "
    "agricultural inputs, growing, raising livestock, aquaculture, buying, "
    "storage, drying, processing, packing and/or exporting agricultural products "
    "in that chain. Investment capital means capital invested in tools and "
    "equipment, heavy machinery, building a factory or production building, "
    "expanding warehouse capacity and installing technology supporting business "
    "activity in that chain. Working capital or investment capital starts from "
    "5,000 US dollars or the riel equivalent. Working capital runs up to 3 years "
    "and investment capital up to 7 years, at 7-9% a year for US dollars and/or "
    "riel. Interest is paid monthly; the principal may be paid monthly, "
    "quarterly, half-yearly or yearly based on cash flow. Conditions: the "
    "criteria above; experience with an existing business operating well; real "
    "estate, being land, a house or a building, or an insurance guarantee letter, "
    "to use as debt security; and the ability to repay. Features: early repayment "
    "of principal without penalty; a grace period on principal of 2 years on "
    "investment capital; and a low interest rate for the agricultural sector.\n"

    "GREEN LOAN. Open to individuals or legal entities acting in the agricultural "
    "value chain and serving the social economy, whose business activity "
    "contributes to protecting the environment and society and to sustainable "
    "national economic development. Short-term working capital runs from 500 to "
    "100,000 US dollars or the riel equivalent, up to 12 months, at 6% to 7.5% a "
    "year. Long-term investment capital runs from 500 to 200,000 US dollars or "
    "the riel equivalent, up to 84 months, at 6.5% to 7.5% a year. Interest is "
    "repaid monthly; the principal may be paid monthly, quarterly, half-yearly or "
    "yearly based on the customer's cash flow. Conditions: an existing business "
    "operating well for at least 1 year; security for the debt, being real "
    "estate, other guarantee letters or a deposit certificate; a business licence "
    "and other legal documents for a legal entity customer; and the ability to "
    "repay. Features: early repayment of principal without penalty; repayment "
    "that flexes with the customer's cash flow; the loan may be used to shift a "
    "business from a traditional model to one resilient to climate change and "
    "sustainable; and other benefits.\n"

    "WHERE ARDB IS. ARDB's head office is at Building No. 168, Street No. 7 "
    "(concrete road), Prek Leap Village, Sangkat Prek Leap, Khan Chroy Changva, "
    "Phnom Penh. ARDB has a branch in Battambang province and mobile offices in a "
    "number of provinces: Banteay Meanchey, Oddar Meanchey, Siem Reap, Stung "
    "Treng, Ratanakiri, Preah Vihear, Kampong Thom, Kampong Cham, Tbong Khmum, "
    "Pursat, Kampong Chhnang, Kampong Speu, Prey Veng, Svay Rieng, Takeo and "
    "Kratie, and it provides credit services everywhere.\n"

    "HOW TO GET IN TOUCH. Enquiries can be made at the head office or through "
    "whichever ARDB representative office is nearest, or by telephone.\n"
    "Head office, Phnom Penh: 023 220 810 / 016 840 505 / 010 599 354 / 069 914 "
    "248 / 012 578 488.\n"
    "Battambang provincial branch, at house number AAA01 E0E1&E2, National Road "
    "No. 5, Anchanh Village, Sangkat O Char, Battambang town, Battambang "
    "province: 017 715 456 / 097 952 2345.\n"
    "Banteay Meanchey representative office, on National Road No. 5, Village 3, "
    "Sangkat Serei Sophoan, Serei Sophoan town: 012 284 566 / 097 328 23 45\n"
    "Oddar Meanchey representative office, Don Ken Sen Chey Village, Sangkat "
    "Samraong, Samraong town: 095 715 456 / 097 326 23 45\n"
    "Siem Reap representative office, Wat Bo Village, Sangkat Sala Kamreuk, Siem "
    "Reap town: 012 201 456.\n"
    "Stung Treng representative office, Reachanukol Village, Sangkat Stung Treng, "
    "Stung Treng town: 099 722 456 / 097 320 23 45\n"
    "Ratanakiri representative office, Phnom Svay Village, Sangkat Boeng "
    "Kansaeng, Banlung town: 011 733 456.\n"
    "Preah Vihear representative office, on Street A10, Lo Et Village, Sangkat "
    "Kampong Pranak, Preah Vihear town: 085 315 456 / 097 302 23 45\n"
    "Kampong Thom representative office, Kampong Thom Village, Sangkat Kampong "
    "Roteh, Stung Sen town: 085 205 456 / 097 303 23 45\n"
    "Kampong Cham representative office, Ta Ong Village, Ta Ong Commune, Chamkar "
    "Leu District: 085 205 456 / 097 303 23 45\n"
    "Tbong Khmum representative office, Cheung Lang Village, Sangkat Suong, Suong "
    "town: 011 994 566 / 097 959 23 45\n"
    "Pursat representative office, Trang Village, Sangkat Svay At, Pursat town: "
    "099 212 456 / 097 329 23 45\n"
    "Kampong Chhnang representative office, Sre Pring Village, Sangkat Kampong "
    "Chhnang, Kampong Chhnang town: 011 214 456.\n"
    "Kampong Speu representative office, Muk Khet Village, Sangkat Roka Thom, "
    "Chbar Mon town: 011 867 456.\n"
    "Prey Veng representative office, Village 4, Sangkat Kampong Leav, Prey Veng "
    "town: 092 722 456 / 097 327 23 45\n"
    "Svay Rieng representative office, Rub Ko Village, Sangkat Prey Chhlak, Svay "
    "Rieng town: 011 667 456.\n"
    "Takeo representative office, Lori Village, Sangkat Roka Knong, Doun Kaev "
    "town: 099 715 456 / 097 322 23 45\n"
    "Kratie representative office, Sre Sdau Village, Sangkat O Russey, Kratie "
    "town: 012 241 456."
)

ENGLISH = {"media-research-faqs": FAQ}
ALLOW_MISSING = {}
